export const EMOJIS = new Map([
  ["accounting", "💸"],
  ["advertising", "📰"],
  ["african-american studies", "🪘📜"],
  ["agriculture", "🌽"],
  ["agronomy", "🚜"],
  ["animal science", "🐭🧬"],
  ["anthropology", "⚱️"],
  ["architecture", "🏛️"],
  ["art", "🎨🖌️"],
  ["art history", "🖼️⚱️"],
  ["asian languages & literatures", "🏮📜"],
  ["asian studies", "🏮📜"],
  ["astronomy", "🌕🔭"],
  ["biology", "🧬🔬"],
  ["botany", "🌱🌿"],
  ["building construction", "👷🛠️"],
  ["business", "👨🏻‍💼💰"],
  ["center for arts in medicine", "👨🏻‍⚕️🎸"],
  ["chemistry", "👩🏻‍🔬🧪"],
  ["classics", "🏛️"],
  ["communication", "🗣️"],
  ["community studies", "👥"],
  ["computer science", "👨‍💻🗿"],
  ["criminal justice", "🚔⚖️"],
  ["criminology", "🚔"],
  ["design", "📝🛠️"],
  ["ecology", "🌍♻️"],
  ["ecology & evolutionary biology", "🌍🧬"],
  ["economics", "📈📊"],
  ["education", "📚🎓"],
  ["electronics", "💻🔌"],
  ["engineering", "👷‍♀️💡"],
  ["english", "📚✍🏻"],
  ["entomology", "🦋🪲"],
  ["environmental science", "🌍👨‍🔬"],
  ["ethnic studies", "🗺🎓"],
  ["exercise sport & health ed", "🏋🏻‍♂️🎓"],
  ["film", "🎥🎬"],
  ["finance", "💰💸"],
  ["fine arts", "🎥🎭"],
  ["food science", "🍔🔬"],
  ["geography", "🗺️📌"],
  ["geological sciences", "🗿🔬"],
  ["geology", "🗿"],
  ["graphic arts", "💻🖌️"],
  ["health & human performance", "❤️"],
  ["health education", "❤️"],
  ["health science", "❤️"],
  ["history", "📜"],
  ["honors", "🎖️"],
  ["horticulture", "🌱"],
  ["hospitality", "🥂"],
  ["human resources", "👥"],
  ["human development", "👥"],
  ["humanities", "👥"],
  ["information science", "👩‍💻"],
  ["information systems & operations management", "👩‍💻"],
  ["institute for excellence in engineering education", "👩‍🏫"],
  ["interdisciplinary studies", "🎓"],
  ["interior design", "🏡"],
  ["international studies", "🌎"],
  ["jazz studies", "🎷"],
  ["journalism", "📰"],
  ["kinesiology & health", "💪🩺"],
  ["languages", "🗣️"],
  ["law", "⚖️"],
  ["liberal arts & sciences", "✒️🏦"],
  ["linguistics", "🗣️"],
  ["literature", "📜"],
  ["management", "💸"],
  ["marketing", "📢"],
  ["materials engineering", "🛠️💡"],
  ["mathematics", "👨‍🏫"],
  ["medicine", "🩺"],
  ["microbiology", "🧬🔬"],
  ["military science", "🪖👩🏻‍🔬"],
  ["music", "🎵"],
  ["nursing", "🩺"],
  ["nutrition", "💊"],
  ["pharmaceutical sciences", "💊🔬"],
  ["philosophy", "⚖️"],
  ["physical education", "🏋🏻‍♂️🎓"],
  ["physics", "👩🏻‍🔬"],
  ["plant pathology", "🪴🧬 "],
  ["political science", "🏛️"],
  ["psychology", "🧠"],
  ["real estate", "🏠💰🔑"],
  ["recreation, parks & tourism", "🎢🌳✈️"],
  ["religion", "🛐"],
  ["science", "👨‍🔬🔬"],
  ["social science", "👥🌎🔍"],
  ["social work", "👥🌎🔍"],
  ["sociology", "👥🌎🔍"],
  ["soil & water sciences", "🌱🌊"],
  ["speech communication", "🗣️"],
  ["sports management", "🏈👨‍💼"],
  ["statistics", "📊"],
  ["student success", "👨🏻‍🎓✨"],
  ["study skills", "🎓🛠️"],
  ["technology", "💻"],
  ["telecommunications", "☎️"],
  ["theater", "🎭"],
  ["theatre & dance", "🎭🕺"],
  ["theology", "✝️"],
  ["tourism studies", "✈️🎓"],
  ["urban planning", "🌉🏢"],
  ["wildlife", "🐈🐘"],
  ["wildlife ecology & conservation", "🐘♻️"],
  ["women", "🚺"],
  ["women's studies", "🚺🎓"],
  ["writing", "✍🏻"],
  ["written & oral communications", "✍🏻🗣️"],
  ["zoology", "🦁"],
  ["FORBIDDEN", "🚫"],
  ["HOT", "🌶️"],
  ["OK", "🆗"],
  ["CAKE", "🍰"],
  ["UNKNOWN", "❓"],
  ["GOOD", "👍"],
  ["FINE", "👌"],
  ["LUCK", "🤞"],
  ["FIRE", "🔥"],
  ["MID", "😑"],
  ["SKULL", "💀"],
]);
